[tool.mypy]
exclude = [
  '.*migrations.*'
]

plugins = [
  'mypy_django_plugin.main',
  'mypy_drf_plugin.main'
]

ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = 'gretel.settings'
